# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='index',
        ),
    ]
